import "./globals.css";
import { Montserrat } from "@next/font/google";
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              {" "}
              <a href="#">About</a>
            </li>
            <li>
              {" "}
              <a href="#">Sign up</a>
            </li>
          </ul>
        </nav>
        <div className={`${montserrat.className}`}>{children}</div>
      </body>
    </html>
  );
}
